[package]
name = "hope"
version = "0.2.1"
edition = "2021"

[profile.dev]
opt-level = 3

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

bam = "0.1.4"
clap = { version = "3.0.14", features = ["derive"] }
